name: HaizServerCore
version: ${version}
main: com.haiz.servercore.HaizServerCore
api-version: "1.20.6"
author: Haiz
description: Sistema de VIP com loja integrada ao Discord.
folia-supported: false

commands:
  haizcore:
    description: Comando administrativo do HaizServerCore.
    usage: /haizcore
    aliases: [hcore, hsc]
    permission: haizcore.admin
  linkar:
    description: Vincula sua conta Minecraft ao Discord para comprar VIPs.
    usage: /linkar <código>
    permission: haiz.vip.link

permissions:
  haizcore.admin:
    description: Acesso total ao HaizServerCore.
    default: op
  haizcore.vip.send:
    description: Permite enviar a mensagem de loja de VIPs no Discord.
    default: op
  haiz.vip.link:
    description: Permite usar /linkar para vincular conta ao Discord.
    default: true
